# Generated by Django 3.2.4 on 2021-06-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210604_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='image/')),
                ('body', models.TextField()),
                ('like', models.SmallIntegerField()),
                ('dislike', models.SmallIntegerField()),
                ('inventory', models.ManyToManyField(to='service.MusicalInventory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.profile')),
            ],
        ),
    ]
