# Generated by Django 3.2.4 on 2021-06-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_song_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('date_created',)},
        ),
        migrations.AddField(
            model_name='song',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='song',
            name='dislike',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='song',
            name='inventory',
            field=models.ManyToManyField(to='service.MusicalInventory', verbose_name='Инвентарь'),
        ),
        migrations.AlterField(
            model_name='song',
            name='like',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.URLField(verbose_name='Ссылка на трек'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название трека'),
        ),
    ]
