# Generated by Django 3.2.4 on 2021-06-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicalinventory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='service.profile'),
        ),
        migrations.AlterField(
            model_name='song',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='service.profile'),
        ),
    ]
