# Generated by Django 3.2.4 on 2021-06-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210607_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='link_sound',
            new_name='iframe_sound',
        ),
    ]
