# Generated by Django 3.2.4 on 2021-06-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20210607_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='actions',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], default='like', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='dislike',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='like',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.AddField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='service.profile'),
        ),
    ]
